on:
  - push
  - pull_request

name: Main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: |
          pip install poetry
          poetry install
          poetry run pre-commit run --all-files --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
        git-version:
          - default  # 2.28.0 or newer
          - '2.21.0'  # https://lore.kernel.org/git/CAKqNo6RJqp94uLMf8Biuo=ZvMZB9Mq6RRMrUgsLW4u1ks+mnOA@mail.gmail.com/T/#u
    name: test (python = ${{ matrix.python-version }}, git = ${{ matrix.git-version }})
    env:
      DARCS_EMAIL: foo <foo@example.com>
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - if: ${{ matrix.git-version != 'default' }}
        run: |
          sudo apt-get install dh-autoreconf libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev
          curl -o git.tar.gz https://mirrors.edge.kernel.org/pub/software/scm/git/git-${{ matrix.git-version }}.tar.gz
          tar -zxf git.tar.gz
          cd git-${{ matrix.git-version }}
          make configure
          ./configure --prefix=/usr
          sudo make install
          which git
          git --version
      - run: |
          export PATH="$PATH:/opt"
          sudo apt-get install -y darcs bzr

          # fossil-linux-x64-2.13.tar.gz, rehosted because the official site deletes older artifacts:
          pip install gdown
          gdown --id 1_gBUGKhs_bponRcgpLlukggWPCR25blF -O ~/fossil.tgz
          tar -xvf ~/fossil.tgz -C /opt

          git config --global user.name "foo"
          git config --global user.email "foo@example.com"
          bzr whoami 'foo <foo@example.com>'

          pip install poetry
          poetry install
          poetry run pytest --verbose --cov --cov-report term-missing

          # Test that get_version() finds Dunamai from the virtual environment and not from the global Python:
          pip install dunamai==1.0.0
          poetry run pytest tests/unit -k test__get_version__
